### PR TITLE
To add FederatedJob

### PR DESCRIPTION
**Pull request by sdminonne**
@marun @font @onyiny-ang @pmorie. 
To add FederatedJob with a pretty basic override (only `spec.parallelism` currently)

Thanks for having a look

### CODE REVIEW

**Comment by marun** [comment]
@sdminonne Please make sure to commit generated code for placement and overrides separate from manual changes.

**Comment by marun** [comment]
Please run `sed -e s+marun/fnord+kubernetes-sigs/federation-v2+` on your changes.

**Comment by sdminonne** [comment]
@marun PTAL

**Comment by marun** [comment]
@sdminonne lgtm except for the last commit.  It isn't necessary to update generated code after adding an adapter since an adapter doesn't affect generated code.  The only reason there were changes is that `apiserver-boot build generated` doesn't render the contents of generated files in a deterministic order.

**Comment by sdminonne** [comment]
@marun thanks for the feedback. 
No problem: I removed the last commit and renamed. 
PTAL

**Comment by marun** [comment]
lgtm, thank you!

**Pull request merged**
